# BINGO Hackaton - Lecture 03
*Luciano Barosi*

**BINGO Collaboration**

In [1]:
import os
import sys
sys.path.append('/home/cosmos/code/cosmos/lessons/')

In [2]:
import lessons

In [3]:
exerc = lessons.Lesson1()

In [4]:
exerc.viewCode()

    def example1(self, **args):
        """
        Example 1:
        Create a **10x10** array with random values
        find the minimum and maximum values
        print the values with 5 decimals
        print the array with 3 decimals
        :param **args: np.array 2D.
        """
        if len(args)!=0:
            Z = args
        else:
            Z = np.random.random((10,10))
        print("NUMPY Example1 - running\n")
        Zmin, Zmax = Z.max(), Z.min()
        print("Zmin=", "{:2.5f}".format(Zmin)," Zmax=","{:2.5f}".format(Zmax))
        print(Z.round(3))
        return

    def example2(self, **args):
        """
        Example 2:
        How to add a border (filled with 0's) around an existing array?

        :param **args: np.array 2D.
        """
        if len(args)!=0:
            Z = args
        else:
            Z = np.ones((5,5))
        print("NUMPY Example2 - running\n")
        Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
        print(Z)


In [6]:
import inspect

In [8]:
inspect.getmembers(exerc, inspect.ismethod)

[('__init__',
  <bound method Lesson1.__init__ of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('all_examples',
  <bound method Lessons.all_examples of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('callExamples',
  <bound method Lessons.callExamples of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example1',
  <bound method Lesson1.example1 of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example10',
  <bound method Lesson1.example10 of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example2',
  <bound method Lesson1.example2 of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example3',
  <bound method Lesson1.example3 of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example4',
  <bound method Lesson1.example4 of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example5',
  <bound method Lesson1.example5 of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example6',
  <bound method Lesson1.example6 of <lessons.Lesson1 object at 0x7f78b438e400>>),
 ('example7',
  <bound

In [30]:
# Same stuff done twice.
print(inspect.getsource(exerc.example1))
exerc.viewCode('example1') 

    def example1(self, **args):
        """
        Example 1:
        Create a **10x10** array with random values
        find the minimum and maximum values
        print the values with 5 decimals
        print the array with 3 decimals
        :param **args: np.array 2D.
        """
        if len(args)!=0:
            Z = args
        else:
            Z = np.random.random((10,10))
        print("NUMPY Example1 - running\n")
        Zmin, Zmax = Z.max(), Z.min()
        print("Zmin=", "{:2.5f}".format(Zmin)," Zmax=","{:2.5f}".format(Zmax))
        print(Z.round(3))
        return

    def example1(self, **args):
        """
        Example 1:
        Create a **10x10** array with random values
        find the minimum and maximum values
        print the values with 5 decimals
        print the array with 3 decimals
        :param **args: np.array 2D.
        """
        if len(args)!=0:
            Z = args
        else:
            Z = np.random.random((10,10))
        print("NU

In [31]:
exercises = exerc.all_examples()
exercises

['example1',
 'example2',
 'example3',
 'example4',
 'example5',
 'example6',
 'example7',
 'example8',
 'example9',
 'example10']

In [32]:
exerc.example1()

NUMPY Example1 - running

Zmin= 0.99991  Zmax= 0.00314
[[0.859 0.022 0.237 0.003 0.839 0.698 0.21  0.452 0.461 0.796]
 [0.259 0.17  0.122 0.276 0.008 0.239 0.08  0.068 0.297 0.15 ]
 [0.917 0.221 0.88  0.706 0.695 0.563 0.177 0.378 0.885 0.071]
 [0.856 0.29  0.944 0.126 0.537 0.176 0.097 0.747 0.665 0.999]
 [0.627 0.161 0.919 0.984 0.947 0.708 0.159 0.78  0.891 0.826]
 [0.499 0.799 0.496 0.716 0.891 0.605 0.403 0.871 0.711 0.056]
 [0.822 0.551 0.22  0.932 0.693 0.413 0.921 0.546 0.488 0.931]
 [0.559 0.653 0.535 0.056 0.764 0.696 0.534 0.525 0.708 0.356]
 [0.299 0.961 1.    0.185 0.009 0.905 0.405 0.193 0.234 0.704]
 [0.624 0.144 0.604 0.094 0.87  0.843 0.28  0.421 0.844 0.021]]


In [17]:
exerc.callExamples()

NUMPY Example1 - running

Zmin= 0.98399  Zmax= 0.00235
[[0.585 0.287 0.241 0.425 0.364 0.638 0.976 0.637 0.889 0.008]
 [0.264 0.002 0.112 0.763 0.473 0.109 0.609 0.13  0.942 0.253]
 [0.461 0.682 0.938 0.684 0.113 0.028 0.141 0.308 0.786 0.984]
 [0.433 0.068 0.878 0.54  0.527 0.886 0.651 0.442 0.315 0.538]
 [0.361 0.934 0.129 0.053 0.874 0.359 0.153 0.543 0.359 0.709]
 [0.255 0.445 0.252 0.095 0.561 0.922 0.24  0.103 0.785 0.158]
 [0.779 0.828 0.026 0.411 0.342 0.755 0.86  0.412 0.297 0.464]
 [0.096 0.583 0.966 0.61  0.753 0.758 0.498 0.434 0.563 0.499]
 [0.584 0.078 0.344 0.401 0.236 0.676 0.249 0.56  0.905 0.61 ]
 [0.488 0.583 0.843 0.11  0.504 0.488 0.682 0.254 0.479 0.764]]
NUMPY Example2 - running

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
NUMPY Example3 - running

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1