In [1]:
import sys
import os
import numpy as np
import inspect
os.getcwd()
os.chdir('../cosmos')

import lessons.lessons1 as lesson1

In [2]:
examples = lesson1.Lesson1
lesson1.countExamples(lesson1.Lesson1)

10

In [3]:
print(examples.example1.__doc__)


        Example1:
        Create a **10x10** array with random values
        find the minimum and maximum values
        


In [4]:
examples.example1()

Zmin= 0.95844  Zmax= 0.00921
[[0.012 0.042 0.957 0.282 0.568 0.339 0.763 0.147 0.152 0.958]
 [0.574 0.492 0.62  0.933 0.197 0.552 0.791 0.552 0.585 0.589]
 [0.891 0.453 0.463 0.645 0.517 0.215 0.756 0.071 0.039 0.625]
 [0.009 0.211 0.28  0.112 0.94  0.859 0.465 0.634 0.558 0.694]
 [0.354 0.529 0.902 0.257 0.124 0.897 0.36  0.388 0.877 0.379]
 [0.137 0.702 0.42  0.785 0.287 0.718 0.819 0.17  0.751 0.306]
 [0.173 0.366 0.765 0.805 0.764 0.048 0.266 0.905 0.204 0.285]
 [0.028 0.037 0.88  0.567 0.28  0.587 0.214 0.728 0.575 0.938]
 [0.512 0.318 0.926 0.037 0.331 0.6   0.926 0.948 0.162 0.115]
 [0.027 0.676 0.676 0.045 0.459 0.434 0.014 0.267 0.601 0.071]]


In [5]:
lesson1.viewCode(examples.example1)

    def example1():
        """
        Example1:
        Create a **10x10** array with random values
        find the minimum and maximum values
        """
        Z = np.random.random((10,10))
        Zmin, Zmax = Z.max(), Z.min()
        print("Zmin=", "{:2.5f}".format(Zmin)," Zmax=","{:2.5f}".format(Zmax))
        print(Z.round(3))
        pass

